FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
WORKDIR /app
EXPOSE 8080
EXPOSE 8081

FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src

# Copy only the src folder contents
COPY src/dotBento.WebApi/ dotBento.WebApi/
COPY src/dotBento.EntityFramework/ dotBento.EntityFramework/

# Set working directory to WebApi
WORKDIR /src/dotBento.WebApi

# Restore dependencies
RUN dotnet restore "dotBento.WebApi.csproj"

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "dotBento.WebApi.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "dotBento.WebApi.dll"]
