@dotBento_WebApi_HostAddress = http://localhost:5072

### Get usage statistics (total users + servers)
GET {{dotBento_WebApi_HostAddress}}/Information/UsageStats
Accept: application/json

###

### Get list of Patreon users
GET {{dotBento_WebApi_HostAddress}}/Information/Patreon
Accept: application/json

###

### Get global leaderboard (no guildId param)
GET {{dotBento_WebApi_HostAddress}}/Information/Leaderboard
Accept: application/json

###

### Get server leaderboard with access check (replace guildId and userId with real values)
GET {{dotBento_WebApi_HostAddress}}/Information/Leaderboard/123/456
Accept: application/json

###