name: Docker - Pre-release

env:
  HUSKY: 0

on:
  push:
    branches:
      - master

jobs:
  github-docker-pre-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Check Commit Message
        run: |
          LAST_COMMIT_MSG=$(git log -1 --pretty=%B)
          if [[ "$LAST_COMMIT_MSG" == *"chore(master): release"* ]]; then
            echo "SKIP_PRERELEASE=true" >> $GITHUB_ENV
          else
            echo "SKIP_PRERELEASE=false" >> $GITHUB_ENV
          fi

      - name: Generate Tag
        if: env.SKIP_PRERELEASE == 'false'
        run: |
          LAST_TAG=$(git describe --tags `git rev-list --tags --max-count=1` | sed 's/-pre-.*//')
          NEW_TAG="${LAST_TAG}-pre-${GITHUB_SHA::8}"
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV

      - name: Create GitHub Pre-release
        if: env.SKIP_PRERELEASE == 'false'
        uses: ncipollo/release-action@v1.14.0
        with:
          name: Pre-release ${{ env.NEW_TAG }}
          tag: ${{ env.NEW_TAG }}
          prerelease: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        if: env.SKIP_PRERELEASE == 'false'
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/thebentobot/dotBento
          tags: |
            type=raw,value=${{ env.NEW_TAG }}

      - name: Set up QEMU
        if: env.SKIP_PRERELEASE == 'false'
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        if: env.SKIP_PRERELEASE == 'false'
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        if: env.SKIP_PRERELEASE == 'false'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }}

      - name: Build and push
        if: env.SKIP_PRERELEASE == 'false'
        uses: docker/build-push-action@v6
        with:
          file: src/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      
      - name: Deploy to Server
        if: env.SKIP_PRERELEASE == 'false'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            # Set the user directory using the secret
            USER_DIR="/${{ secrets.SERVER_USERNAME }}"
            
            # Update the docker-compose.yml file with the new pre-release image tag
            sed -i 's|ghcr.io/thebentobot/dotbento:[^ ]*|ghcr.io/thebentobot/dotbento:${{ env.NEW_TAG }}|' $USER_DIR/bento/docker-compose.yml
            
            # Pull the new image and redeploy the service using 'docker compose' (without the hyphen)
            docker compose -f $USER_DIR/bento/docker-compose.yml pull bot-sta
            docker compose -f $USER_DIR/bento/docker-compose.yml up -d bot-sta