name: release-please

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Determine Release Type
        run: |
          LAST_COMMIT_MSG=$(git log -1 --pretty=%B)
          if [[ "$LAST_COMMIT_MSG" == *"chore(master): release"* ]]; then
            echo "PRERELEASE=false" >> $GITHUB_ENV
          else
            echo "PRERELEASE=true" >> $GITHUB_ENV
          fi

      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: simple
          package-name: dotBento
          token: ${{ secrets.PAT }}
          include-v-in-tag: true
          prerelease: ${{ env.PRERELEASE }}
