name: Release Workflow

on:
  push:
    branches:
      - master
    paths:
      - 'release-dates.md' # Trigger release when this file changes
      - '**'               # Trigger for any other change

jobs:
  release:
    if: github.event.push.paths == 'release-dates.md'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Release
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: simple
          package-name: dotBento
          token: ${{ secrets.PAT }}
          include-v-in-tag: true
          prerelease: false

  prerelease:
    if: github.event.push.paths != 'release-dates.md'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Prerelease
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: simple
          package-name: dotBento
          token: ${{ secrets.PAT }}
          include-v-in-tag: true
          prerelease: true
