name: release-please

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  prerelease:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Other steps to setup and configure
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: simple
          package-name: dotBento
          token: ${{ secrets.PAT }}
          include-v-in-tag: true
          prerelease: true
          command: github-release

  release:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Other steps to setup and configure
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: simple
          package-name: dotBento
          token: ${{ secrets.PAT }}
          include-v-in-tag: true
          prerelease: false
          