name: release-please

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Show Current Directory
        run: pwd

      - name: List Directory Contents
        run: ls -la

      - name: Show Last Commit Message
        run: git log -1 --pretty=%B

      - name: Set PRERELEASE Variable
        run: |
          if git log -1 --pretty=%B | grep -q "chore(master): release"; then
            echo "PRERELEASE=false" >> $GITHUB_ENV
          else
            echo "PRERELEASE=true" >> $GITHUB_ENV
          echo "SET_PRERELEASE=$PRERELEASE" >> $GITHUB_ENV

      - name: Show SET_PRERELEASE
        run: echo "SET_PRERELEASE is $SET_PRERELEASE"

      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: simple
          package-name: dotBento
          token: ${{ secrets.PAT }}
          include-v-in-tag: true
          prerelease: ${{ env.SET_PRERELEASE }}
