name: Manual Merge for Release

on:
  workflow_dispatch:
    inputs:
      prNumber:
        description: 'Pull Request Number to Merge into Master as an release'
        required: true
        type: number

jobs:
  merge-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Fetch PR
        run: |
          git fetch origin pull/${{ github.event.inputs.prNumber }}/head:pr-${{ github.event.inputs.prNumber }}
          git checkout pr-${{ github.event.inputs.prNumber }}
          git merge master --no-edit --allow-unrelated-histories
          git push origin HEAD:master
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

      - name: Confirm Merge
        run: echo "PR #${{ github.event.inputs.prNumber }} merged into master"
